# Generated by Django 4.2.7 on 2023-11-19 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbusinessunit',
            name='business_unit_manager',
            field=models.ForeignKey(default=1, help_text='The user that manages the business unit. Cannot be null.', on_delete=django.db.models.deletion.CASCADE, related_name='org_business_units', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
