# Generated by Django 4.2.7 on 2023-11-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AM', 'Account Manager'), ('BUM', 'Business Unit Manager'), ('SD', 'Sales Director')], default='AM', max_length=3),
        ),
    ]
