# Generated by Django 4.2.6 on 2023-11-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_planner', '0002_alter_mediagroup_options_alter_brand_agency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='name',
        ),
    ]
