# Generated by Django 4.2.7 on 2023-11-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_planner', '0002_orgbusinessunit_business_unit_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='abandoned_date',
            field=models.DateField(blank=True, help_text='Date the opportunity was abandoned', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='disabled_date',
            field=models.DateField(blank=True, help_text='Date the opportunity was disabled', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='expired_date',
            field=models.DateField(blank=True, help_text='Date the opportunity expired', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lost_date',
            field=models.DateField(blank=True, help_text='Date the opportunity was lost', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='won_date',
            field=models.DateField(blank=True, help_text='Date the opportunity was won', null=True),
        ),
    ]
