# Generated by Django 4.2.7 on 2023-11-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_planner', '0003_opportunity_abandoned_date_opportunity_disabled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
